"""Generate responsive WebP and AVIF variants for the public image catalog.

Run with Python and Pillow. Original catalog files remain the full-resolution
fallback and are never overwritten.
"""

from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "public" / "images" / "catalog"
ADDITIONAL_SOURCES = (
    ROOT / "public" / "images" / "norwell-hero.webp",
    ROOT / "public" / "images" / "norwell-salmon-dish.webp",
    ROOT / "public" / "images" / "people" / "mai-tonheim-consulate.jpg",
    ROOT / "public" / "images" / "people" / "mai-tonheim-diplomacy.jpg",
    ROOT / "public" / "images" / "people" / "mai-tonheim-norway-brazil.jpg",
    ROOT / "public" / "images" / "people" / "mai-tonheim-portrait.jpg",
    ROOT / "public" / "images" / "people" / "mai-tonheim-salmon-preparation.png",
    ROOT / "public" / "images" / "people" / "mai-tonheim-salmon-presentation.jpg",
)
OUTPUT_DIR = ROOT / "public" / "images" / "responsive"
STANDARD_WIDTHS = (480, 800, 1200, 1600)
MAX_WIDTHS = {
    "culinary-01": 1200,
    "culinary-02": 800,
    "culinary-03": 800,
    "culinary-04": 1200,
    "culinary-05": 800,
    # Used only as the full-size Open Graph image; no responsive DOM variants.
    "fisherman-salmon": 0,
    "norway-farm-wide": 1200,
    "norway-fjord": 1200,
    "norwell-hero": 1600,
    "norwell-salmon-dish": 800,
    "mai-tonheim-consulate": 800,
    "mai-tonheim-diplomacy": 480,
    # The source is only 388 px wide; keep the compact original as fallback.
    "mai-tonheim-norway-brazil": 0,
    "mai-tonheim-portrait": 800,
    "mai-tonheim-salmon-preparation": 800,
    "mai-tonheim-salmon-presentation": 1200,
    "processing": 800,
    "salmon-eggs": 800,
    "salmon-farm": 800,
    "salmon-fillet": 1200,
    "salmon-origin": 1200,
    "salmon-portions": 1200,
    "salmon-smoked": 1200,
    "salmon-underwater": 1600,
    "salmon-whole": 1200,
    "smolt": 800,
}

# Art-directed crops avoid stretching panoramic source files inside tall hero
# frames. Each tuple is: source, output stem, aspect ratio, focal x, widths.
ART_DIRECTED_CROPS = (
    (ROOT / "public" / "images" / "norwell-hero.webp", "norwell-hero-mobile", 3 / 4, 0.535, (480, 694)),
    (SOURCE_DIR / "norway-fjord.webp", "norway-fjord-portrait", 4 / 5, 0.5, (540, 1080)),
)


def target_widths(stem: str, native_width: int) -> list[int]:
    max_width = min(native_width, MAX_WIDTHS[stem])
    return [width for width in STANDARD_WIDTHS if width <= max_width]


def save_variants(source: Image.Image, stem: str, widths: tuple[int, ...] | list[int]) -> None:
    for width in widths:
        height = round(source.height * width / source.width)
        resized = source.resize((width, height), Image.Resampling.LANCZOS)
        output_stem = f"{stem}-{width}"

        resized.save(
            OUTPUT_DIR / f"{output_stem}.webp",
            "WEBP",
            quality=80,
            method=6,
            optimize=True,
        )
        resized.save(
            OUTPUT_DIR / f"{output_stem}.avif",
            "AVIF",
            quality=58,
            speed=6,
        )


def generate() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Everything in this dedicated directory is generated by this script.
    for generated_path in OUTPUT_DIR.glob("*"):
        if generated_path.is_file():
            generated_path.unlink()

    source_paths = [*sorted(SOURCE_DIR.glob("*.webp")), *ADDITIONAL_SOURCES]
    for source_path in source_paths:
        with Image.open(source_path) as source:
            source = ImageOps.exif_transpose(source).convert("RGB")
            save_variants(source, source_path.stem, target_widths(source_path.stem, source.width))

    for source_path, output_stem, aspect_ratio, focal_x, widths in ART_DIRECTED_CROPS:
        with Image.open(source_path) as source:
            source = ImageOps.exif_transpose(source).convert("RGB")
            crop_width = min(source.width, round(source.height * aspect_ratio))
            crop_height = min(source.height, round(crop_width / aspect_ratio))
            focal_center = round(source.width * focal_x)
            left = max(0, min(source.width - crop_width, focal_center - crop_width // 2))
            top = max(0, (source.height - crop_height) // 2)
            crop = source.crop((left, top, left + crop_width, top + crop_height))
            save_variants(crop, output_stem, widths)


if __name__ == "__main__":
    generate()
